### PR TITLE
Metrics + rooms

### PR DESCRIPTION
**Pull request by carolineychen8**

### CODE REVIEW

**Review by arulandu — APPROVED** [review]
should be good.

**Review by arulandu — CHANGES_REQUESTED** [review]
your room schema doesn't make sense. it doesn't match the schema defined in the hotel API docs.

**Comment by liondon** [comment]
bug fixed. examples and more details added. All the hotel endpoints openAPI work with correct content/example now. 

But there are a lot of duplicate codes, need to refactor them in the future.

**Review by arulandu — DISMISSED** [review]
looks good. try to separate the duplicated code into components in a separate folder and ref them in. I'll merge once that's done.

**Review by liondon — APPROVED** [review]
reivewed, modified, and tested. (Though no one reviewed my edits...)

**Pull request merged**
